"""Gemini CLI agentic variation operator — v1."""

from gpu_forecasters.agentic_variation.gemini_cli.v1.models import (
    BaselineFeedbackEntry,
    ExperimentConfig,
    PerToolCallHook,
    PostRunContext,
    PostRunHook,
    PromptContext,
    PromptRenderer,
    RepeatedRunSummary,
    ThinkingLevel,
    ToolCallContext,
    TrajectoryRecord,
    TrimulRunResult,
    copy_kernel_files,
    default_system_prompt_renderer,
    default_user_prompt_renderer,
)
from gpu_forecasters.agentic_variation.gemini_cli.v1.orchestrator import (
    IMAGE_TAG,
    MCP_TOOL_NAME,
    RunLayout,
    clear_partial_runs,
    dispatch_per_tool_call_hooks,
    dispatch_post_run_hooks,
    run_experiment,
)
from gpu_forecasters.agentic_variation.gemini_cli.v1.prompts import (
    format_feedback_summary,
    render_system_prompt,
    render_user_prompt,
)
from gpu_forecasters.agentic_variation.gemini_cli.v1.results import (
    RESULT_FILENAME,
    RUN_DIR_PREFIX,
    TRAJECTORY_FILENAME,
    RunArtifacts,
    best_record,
    compute_summary,
    load_run_artifacts,
    load_trajectory,
)

__all__ = [
    "BaselineFeedbackEntry",
    "ExperimentConfig",
    "IMAGE_TAG",
    "MCP_TOOL_NAME",
    "PerToolCallHook",
    "PostRunContext",
    "PostRunHook",
    "PromptContext",
    "PromptRenderer",
    "RESULT_FILENAME",
    "RUN_DIR_PREFIX",
    "RepeatedRunSummary",
    "RunArtifacts",
    "RunLayout",
    "TRAJECTORY_FILENAME",
    "ThinkingLevel",
    "ToolCallContext",
    "TrajectoryRecord",
    "TrimulRunResult",
    "best_record",
    "clear_partial_runs",
    "compute_summary",
    "copy_kernel_files",
    "default_system_prompt_renderer",
    "default_user_prompt_renderer",
    "dispatch_per_tool_call_hooks",
    "dispatch_post_run_hooks",
    "format_feedback_summary",
    "load_run_artifacts",
    "load_trajectory",
    "render_system_prompt",
    "render_user_prompt",
    "run_experiment",
]
